name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        version: 12
        # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
        registry-url: https://registry.npm.taobao.org/
    - name: Init PRIVATE_KEY 
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa 47.102.143.46 >> ~/.ssh/known_hosts
    - name: Install dependence
      run: yarn 
    - name: Build vue
      run: yarn run build
    - name: Deploy
      run: rsync -az --delete ./dist/* root@47.102.143.46:/home/html/admin

    